SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = 50
ASTEROID_SPAWN_RATE = 3  # seconds

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 180  # degrees per second
PLAYER_SPEED = 200

SHOT_RADIUS = 3
PLAYER_SHOOT_SPEED = 300